### ISSUE TITLE
Certify this implementation

### ISSUE THREAD

**Issue by Thihup** [beckchr/juel#101]
Are there any plans to keep this project active?
Now the TCKs for the Expression Language are available and we can certify the implementation ourselves.

So as this project already implements a large portion of the spec, it would just require to implement the missing bits and certify this implementation.

I can help setting up the TCK if you will.

If this project is not active anymore, would you mind if I fork it and start implementing the missing features?

(PS: Now the main package is "jakarta" instead of "javax", so it would be needed to release a major version of this library)

Some links:
- https://jakarta.ee/specifications/expression-language/4.0/
- https://www.agilejava.eu/2021/02/05/compatible-implementations/

**Comment by beckchr** [comment]
Hi, this project is no longer under active development. Feel free to fork it!

**Comment by Thihup** [comment]
Ok! Thanks!
