### ISSUE TITLE
Parsing with backslashes

### ISSUE THREAD

**Issue by laurentvaills** [beckchr/juel#85]
Hi,

I'm trying to write an expression in order to produce the following String : "foo\quix" (foo is constant but quix will be the value of a variable).

I tried to do this with the following code, but it seems the backslashes are not well handled : 
```java
ExpressionFactory factory = new ExpressionFactoryImpl();
String expression = "foo\\\\${bar}";
SimpleContext context = new SimpleContext();
context.setVariable("bar", factory.createValueExpression("quix", String.class));
ValueExpression expr = factory.createValueExpression(context, expression , String.class);

System.out.println(expr.getValue(context));
```
On stdout, I get "foo\${bar}" but I expected to get "foo\quix" .

How can I achieve this ?

Regards,
Laurent.

**Comment by beckchr** [comment]
Please try

String expression = "foo${'\\\\'}${bar}";

**Comment by laurentvaills** [comment]
Thanks for the work-around, that works.
I was wondering, if that was a bug in the parser indeed.
