### ISSUE TITLE
What about String concatenation according to the EL 3.0 spec

### ISSUE THREAD

**Issue by phortx** [beckchr/juel#88]
`${"foo" += "bar"}` does juel support it? If not: Will string concatenation be implemented?

**Comment by beckchr** [comment]
JUEL implements a specification. There is no operator for string concatenation ("+") and there's no assignment ("=", "+=") at all. However, you may concatenate expressions:

    ${'foo'}${'bar'}

will evaluate to the string `"foobar"`.

**Comment by tandraschko** [comment]
Sorry to ask in the ticket but are there plans to implement EL 3.0?
There is a example with += available in a slide here: http://de.slideshare.net/reza_rahman/whats-new-with-expression-language-in-java-ee-7

**Comment by arjantijms** [comment]
@beckchr @tandraschko Also curious about any EL 3.0 plans for UEL.

**Comment by dzmitry-kankalovich** [comment]
Hello @beckchr, just curious as well if there are any plans for EL 3.0? Since Java 8 and it's streams and lambdas EL 3.0 gives significant boost in capabilities, would be nice to have it in JUEL :)

**Comment by beckchr** [comment]
JUEL 3... Probably not.

**Comment by arjantijms** [comment]
@beckchr You more or less stopped with JUEL?

**Comment by beckchr** [comment]
Yes, more or less. Will do bugfixes though.

**Comment by arjantijms** [comment]
Ok, thanks for the reply ;)
