### ISSUE TITLE
Problems to determine the type of an expression for a Java Generics class

### ISSUE THREAD

**Issue by aknuth** [beckchr/juel#93]
I've simplified our classes a little bit, so please don't ask why e.g. WPDEnum is an empty class.

```
public class WPDEnum {}
```

```
public class DueFieldWPDEnum<T extends WPDEnum>  {
	private T content;

	public DueFieldWPDEnum(T content) {
		this.content = content;
	}

	public T getContent() {
		return content;
	}

}
```

```
public class YesNo extends WPDEnum {
	public static final YesNo Yes = new YesNo();
	public static final YesNo No = new YesNo();
}
```
Business Object class:
```
public class Bom {
	private DueFieldWPDEnum<YesNo> field1 = new DueFieldWPDEnum<>(YesNo.No);

	public DueFieldWPDEnum<YesNo> getField1() {
		return field1;
	}
}
```
The test case
```
public class JuelTest {

	protected final static ExpressionFactory factory = new de.odysseus.el.ExpressionFactoryImpl();
	private SimpleContext context = new SimpleContext();
	private String expression = "#{bm.field1.content}";
	private Object base = new Bom();
	private ValueExpression ve = factory.createValueExpression(context, expression, Object.class);

	@Test
    public void startTest1() {
		factory.createValueExpression(context, "#{bm}", base.getClass()).setValue(context, base);
		Object o = ve.getValue(context);
		assertTrue(o.getClass()==YesNo.class);
    }

	@Test
    public void startTest2() {
		factory.createValueExpression(context, "#{bm}", base.getClass()).setValue(context, base);
		Class<?> cls = ve.getType(context);
		assertTrue(cls==YesNo.class);
    }

}
```

Test1 works (determine the class by value), Test2 fails because cls is WPDEnum.class.
Am I doing anything wrong or is this a bug ?

**Comment by beckchr** [comment]
This is not a bug. The `getType()` method does not answer the type of the stored value, but the "property type". To store a given value, it must be assignable to the property type. In your case, the property is `DueFieldWPDEnum.content`.

From the documentation of `ValueExpression.getType()`:

> Evaluates the expression relative to the provided context, and returns the most general type that is acceptable for an object to be passed as the value parameter in a future call to the setValue(ELContext, Object) method.

Also, the type will be a raw type, i.e. without generic information. In your code, `T extends WDEnum` should lead to `WDEnum`. True?

**Comment by aknuth** [comment]
Thanks for your quick response.

I know that getType() answers the property type. That's what I need to get (because the value can be null). But what about a property type of "T" ? T is specified in the Bom class. It's YesNo in this context.

So, I would expect to get YesNo.class instead of WPDEnum.class --> see the assertion.

But I might misunderstand the documentation of ```ValueExpression.getType()```

**Comment by beckchr** [comment]
Generic type information is thrown away when evaluating types. The code that does the work in this case is `javax.el.BeanELResolver`. It uses Java Bean property descriptors. However, you might want to check other implementations.

**Comment by aknuth** [comment]
Good hint. I've had a look inside the code - just reflection on the class itself. Impossible to gather the real type for "T".
Ok, I will close this issue. Thanks for the support.
