### ISSUE TITLE
Using JUEL in JSP EE Application

### ISSUE THREAD

**Issue by abdelkaderl** [beckchr/juel#94]
Hello,

Thanks for this very nice work for using EL Expression.

But, i have an issue when using JSP pages, i have an exception : 

Etat HTTP 500 - java.lang.LinkageError: loader constraint violation: when resolving interface method "javax.servlet.jsp.JspApplicationContext.getExpressionFactory()Ljavax/el/ExpressionFactory;" the class loader (instance of org/apache/jasper/servlet/JasperLoader) of the current class, org/apache/jsp/alive_jsp, and the class loader (instance of org/apache/catalina/loader/StandardClassLoader) for resolved class, javax/servlet/jsp/JspApplicationContext, have different Class objects for the type avax/el/ExpressionFactory; used in the signature

i think theris a conflict between JUEL and el-api provided by tomcat! 

do you have any idea?

thanks.

**Comment by beckchr** [comment]
Which tomcat version do you use and what JUEL jars do you have in your WEB-INF/lib?

**Comment by abdelkaderl** [comment]
Hi, 
thanks for your quick answer.

im using maven dependencies : 

<dependency>
	      <groupId>de.odysseus.el</groupId>
	      <artifactId>juel-api</artifactId>
	      <version>2.2.7</version>
</dependency>
<dependency>
			<groupId>de.odysseus.el</groupId>
			<artifactId>juel-impl</artifactId>
			<version>2.2.7</version>
</dependency>

and tomcat 6.

**Comment by abdelkaderl** [comment]
I even tried this : "juel-spi", But I still have the exception, I think it is related to the libraries provided by tomcat

**Comment by beckchr** [comment]
Please try without juel-api, only juel-spi and juel-impl.

**Comment by abdelkaderl** [comment]
Yes iv already tried this, and i got this error : ExpressionFactory cannot be resolved to a type in some JAVA classes.

**Comment by beckchr** [comment]
Can't you use a newer tomcat?

**Comment by abdelkaderl** [comment]
Unfortunately no, the application I'm working on now, supports just tomcat 6!

the JUEL implementation dosnt support JSP file ?

**Comment by abdelkaderl** [comment]
If theris no solution ! i think ill use a servlet to print my output as HTML content !

**Comment by beckchr** [comment]
Yes, it supports JSP. You have a class loading issue.

Did you try putting the JUEL jars (spi & impl) into tomcat's /lib folder? In addition, as a last resort, try to replace tomcat's lib/el-api.jar with juel-api-xxx.jar.

**Comment by abdelkaderl** [comment]
Hey again,

Yes, it works for me!

i put the JUEL jars (spi & impl)  into tomcat/lib/, and in my pom.xml  iv changed the scope to provided => And it works now.

Thanks a lot.
Have a nice day.

**Comment by abdelkaderl** [comment]
Im trying the last solution, replacing => tomcat's lib/el-api.jar with juel-api-xxx.jar.

i'll be back to you with results.

**Comment by abdelkaderl** [comment]
Finally, i changed just the scope to provided and it works now !

thanks a lot for your help.

**Comment by beckchr** [comment]
Great!
